# Generated by Django 2.0.5 on 2018-09-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('apartment_nr', models.SmallIntegerField(null=True)),
                ('building_nr', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('death_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=17, null=True)),
                ('status', models.CharField(default=0, max_length=200)),
                ('return_time', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservaton_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBorrow.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Publishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('lock', models.BooleanField(default=False)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('books_limit', models.SmallIntegerField(default=2)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookBorrow.Address')),
            ],
        ),
        migrations.AddField(
            model_name='bookqueue',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBorrow.Reader'),
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Country'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Publishment'),
        ),
        migrations.AddField(
            model_name='book',
            name='queue',
            field=models.ManyToManyField(through='BookBorrow.BookQueue', to='BookBorrow.Reader'),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBorrow.Country'),
        ),
    ]
