# Generated by Django 2.0.5 on 2018-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='english_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='polish_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
