# Generated by Django 2.1.2 on 2018-10-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookqueue',
            old_name='reservaton_date',
            new_name='reservation_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Language'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookBorrow.Country'),
        ),
    ]
