# Generated by Django 2.1.2 on 2018-10-12 20:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0002_auto_20181012_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2018, 10, 11, 22, 36, 59, 586543))]),
        ),
        migrations.AlterField(
            model_name='reader',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2018, 10, 11, 22, 36, 59, 586543))]),
        ),
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator]),
        ),
    ]
