# Generated by Django 2.0.5 on 2018-09-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0003_auto_20180930_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='bookqueue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookqueue',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='publishment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookQueue',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Publishment',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
