# Generated by Django 2.1.2 on 2018-10-12 20:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0003_auto_20181012_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2018, 10, 11, 22, 42, 28, 317826))]),
        ),
        migrations.AlterField(
            model_name='reader',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2018, 10, 11, 22, 42, 28, 317826))]),
        ),
    ]
