# Generated by Django 2.1.2 on 2018-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0003_auto_20181014_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Available'), ('1', 'Borrowed'), ('2', 'Reserved')], default='0', max_length=10),
        ),
    ]
