# Generated by Django 2.1.2 on 2018-10-12 20:50

import BookBorrow.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0004_auto_20181012_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True, validators=[BookBorrow.validators.no_future_date]),
        ),
        migrations.AlterField(
            model_name='reader',
            name='birth_date',
            field=models.DateField(null=True, validators=[BookBorrow.validators.no_future_date]),
        ),
    ]
