# Generated by Django 2.1.2 on 2018-10-14 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0005_auto_20181014_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='reader',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
