# Generated by Django 2.0.5 on 2018-10-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0006_auto_20181001_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishment',
            name='country',
        ),
    ]
