# Generated by Django 2.1.2 on 2018-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0009_auto_20181104_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='BookBorrow.Author'),
        ),
    ]
