# Generated by Django 2.0.5 on 2018-10-01 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0010_auto_20181001_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(max_length=4, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
