# Generated by Django 2.1.2 on 2018-11-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0010_auto_20181104_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
