# Generated by Django 2.0.5 on 2018-10-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0012_auto_20181001_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='BookBorrow.Address'),
        ),
    ]
