# Generated by Django 2.1.2 on 2018-11-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0013_auto_20181112_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='polish_name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='polish_name',
        ),
    ]
