# Generated by Django 2.0.5 on 2018-10-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBorrow', '0014_auto_20181004_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='lock',
            new_name='account_lock',
        ),
    ]
